version: 2

jobs:
    build_and_test:

        # Specify the Xcode version to use.
        macos:
            xcode: "10.1.0"
        shell: /bin/bash --login -o pipefail
        steps:
            - checkout

            # Download CocoaPods specs via HTTPS (faster than Git) and install CocoaPods.
            - run:
                name: Fetch CocoaPods Specs
                command: |
                    curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
                    pod install --verbose

            # - run:
            #     name: Install Jazzy
            #     command: gem install jazzy

            # Run tests.
            - run:
                name: Build and run tests
                command: xcodebuild \
                            -workspace 'EngaugeTx.xcworkspace' \
                            -scheme 'EngaugeTx' \
                            -sdk iphonesimulator \
                            -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' \
                            CODE_SIGNING_REQUIRED=NO \
                            clean build test


            - store_test_results:
                path: output/scan
            - store_artifacts:
                path: output

    deploy_to_cocoapods:
        macos:
            xcode: "10.1.0"
        steps:
            - run:
                name: Deploy Script
                command: ./deploy_release.sh

workflows:
    version: 2
    build-workflow:
        jobs:
            - build_and_test:
                filters:
                    tags:
                        only: /[0-9]+(\.[0-9]+)*/
            - deploy_to_cocoapods:
                requires:
                    - build_and_test
                filters:
                    tags:
                        only: /[0-9]+(\.[0-9]+)*/