version: 2

jobs:
    build_and_test:

        # Specify the Xcode version to use.
        macos:
            xcode: "10.1.0"
        shell: /bin/bash --login -o pipefail
        steps:
            - checkout

            # Download CocoaPods specs via HTTPS (faster than Git) and install CocoaPods.
            - run:
                name: Fetch CocoaPods Specs
                command: |
                    curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
                    pod install --verbose

            # Run tests.
            - run:
                name: Build and run tests
                command: xcodebuild -workspace 'EngaugeTx.xcworkspace' -scheme 'EngaugeTx' clean build test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= | xcpretty --color --report junit


            - store_test_results:
                path: output/scan
            - store_artifacts:
                path: output

    # Deploys to the SDK repository: https://github.com/medullan/engauge-tx-pod-specs/tree/master/EngaugeTx
    # This consists of pushing the podspec file.
    build_and_push_to_repo:
        macos:
            xcode: "10.1.0"
        steps:
            - checkout

             # Download CocoaPods specs via HTTPS (faster than Git) and install CocoaPods.
            - run:
                name: Fetch CocoaPods Specs
                command: |
                    curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
                    pod install --verbose

            - run:
                name: Deploy Script
                command: sh deploy_release.sh

workflows:
    version: 2
    build-workflow:
        jobs:
            - build_and_test:
                filters:
                    tags:
                        only: /.*/
            - build_and_push_to_repo:
                requires:
                    - build_and_test
                filters:
                    tags:
                        only: /[0-9]+(\.[0-9]+)+(-[A-Za-z0-9\.]+)?/